// frontend/src/app/dashboard/dashboard.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import {
  Observable,
  Subscription,
  catchError,
  switchMap,
  timer,
  EMPTY,
  tap,
} from 'rxjs';
import { CpuUsage, User } from 'models';
import moment from 'moment';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css'],
})
export class DashboardComponent {
  latestUserCpuUsage: string = '';
  latestUserTimestamp: string = '';
  userLastHourAvgUsage: string = '';
  usersWithAboveAvgUsage: Array<{ user: User; userAvg: number }> | null = null;
  userPercentile: string = '';
  private subscription: Subscription = new Subscription();

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.subscription = timer(0, 5000)
      .pipe(
        switchMap(() => {
          return this.fetchData();
        })
      )
      .subscribe();
    this.subscription = timer(0, 5000)
      .pipe(
        switchMap(() => {
          return this.fetchLastHourAvg();
        })
      )
      .subscribe();
    this.subscription = timer(0, 5000)
      .pipe(
        switchMap(() => {
          return this.fetchUsersWithAboveAvgUsage();
        })
      )
      .subscribe();
    this.subscription = timer(0, 5000)
      .pipe(
        switchMap(() => {
          return this.fetchUserPercentile();
        })
      )
      .subscribe();
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  private fetchData(): Observable<CpuUsage> {
    return this.http.get<CpuUsage>('http://localhost:8080/cpu-usage').pipe(
      catchError((error: any) => {
        console.error('Error fetching CPU usage data:', error);
        return EMPTY;
      }),
      switchMap((data: CpuUsage) => {
        this.latestUserCpuUsage = data.usage.toFixed(2);
        this.latestUserTimestamp = this.getFormattedTime(data.timestamp);
        return EMPTY;
      })
    );
  }

  private fetchLastHourAvg(): Observable<number> {
    return this.http.get<number>('http://localhost:8080/last-hour-avg').pipe(
      catchError((error: any) => {
        console.error('Error fetching last hour average:', error);
        return EMPTY;
      }),
      switchMap((avg: number) => {
        this.userLastHourAvgUsage = avg.toFixed(2);
        return EMPTY;
      })
    );
  }

  private fetchUsersWithAboveAvgUsage(): Observable<Array<{
    user: User;
    userAvg: number;
  }> | null> {
    return this.http
      .get<Array<{ user: User; userAvg: number }> | null>(
        'http://localhost:8080/above-avg-usage-users'
      )
      .pipe(
        catchError((error: any) => {
          console.error(
            'Error fetching users with above average usage:',
            error
          );
          return EMPTY;
        }),
        tap((data: Array<{ user: User; userAvg: number }> | null | null) => {
          if (data) {
            this.usersWithAboveAvgUsage = data
              .sort((a, b) => {
                return b.userAvg - a.userAvg;
              })
              .map((user) => {
                return {
                  user: user.user,
                  userAvg: parseFloat(
                    `${user.userAvg.toFixed(1)}${
                      user.userAvg % 1 === 0 ? '.0' : ''
                    }`
                  ),
                };
              });
          }
        })
      );
  }

  private fetchUserPercentile(): Observable<number> {
    return this.http.get<number>('http://localhost:8080/user-percentile').pipe(
      catchError((error: any) => {
        console.error('Error fetching last hour average:', error);
        return EMPTY;
      }),
      switchMap((avg: number) => {
        this.userPercentile = avg.toFixed(2);
        return EMPTY;
      })
    );
  }

  private getFormattedTime(timestamp: number): string {
    return moment(timestamp).format('HH:mm:ss');
  }
}

// frontend/src/Dashboard.tsx
import { useState, useEffect } from 'react';
import axios from 'axios';
import moment from 'moment';
import { CpuUsage } from 'models';

const Dashboard = () => {
  const [cpuUsage, setCpuUsage] = useState<CpuUsage>();
  const [lastHourAvg, setLastHourAvg] = useState<number | null>(null);

  useEffect(() => {
    fetchData();

    const interval = setInterval(fetchData, 5000);

    return () => clearInterval(interval);
  }, []);

  const fetchData = async () => {
    try {
      const response = await axios.get('http://localhost:8080/cpu-usage');

      const data = response.data as CpuUsage;

      setCpuUsage(data);

      const _lastHourAvg = await axios.get(
        'http://localhost:8080/last-hour-avg'
      );

      const lastHourAvg = _lastHourAvg.data as number | null;

      setLastHourAvg(lastHourAvg);
    } catch (error) {
      console.error('Error fetching CPU usage data:', error);
    }
  };

  return (
    <div>
      <h1>CPU Usage Dashboard</h1>
      {cpuUsage && (
        <p>
          {cpuUsage.usage}% was the CPU usage at{' '}
          {moment(cpuUsage.timestamp).format('HH:mm:ss')}
        </p>
      )}

      {lastHourAvg && (
        <p>{lastHourAvg}% was the average CPU usage in the last hour</p>
      )}
    </div>
  );
};

export default Dashboard;
