// frontend-react/src/pages/Dashboard.tsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import axios from 'axios';
import { CpuUsage, User } from 'models';
import { useEffect, useState } from 'react';
import {
  faSignal,
  faPercent,
  faClock
} from '@fortawesome/free-solid-svg-icons';
import moment from 'moment';

export default function Dashboard() {
  const [latestUserCpuUsage, setLatestUserCpuUsage] = useState<CpuUsage | null>(
    null
  );
  const [userLastHourAvgUsage, setUserLastHourAvgUsage] = useState<
    number | null
  >(null);
  const [usersWithAboveAvgUsage, setUsersWithAboveAvgUsage] = useState<Array<{
    user: User;
    userAvg: number;
  }> | null>(null);
  const [userPercentile, setUserPercentile] = useState<number | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [
          latestUsageResponse,
          lastHourAvgResponse,
          aboveAvgUsersResponse,
          userPercentileResponse
        ] = await Promise.all([
          axios.get<CpuUsage | null>('http://localhost:8080/cpu-usage'),
          axios.get<number>('http://localhost:8080/last-hour-avg'),
          axios.get<Array<{ user: User; userAvg: number }> | null>(
            'http://localhost:8080/above-avg-usage-users'
          ),
          axios.get<number>('http://localhost:8080/user-percentile')
        ]);

        setLatestUserCpuUsage(latestUsageResponse.data);
        setUserLastHourAvgUsage(lastHourAvgResponse.data);
        setUsersWithAboveAvgUsage(aboveAvgUsersResponse.data);
        setUserPercentile(userPercentileResponse.data);
      } catch (error) {
        console.error('Error fetching data:', error);
      }
    };

    fetchData();

    const intervalId = setInterval(fetchData, 30000);

    return () => clearInterval(intervalId);
  }, []);

  return (
    <>
      <div className="ml-10 p-5">
        <header className="pb-5">
          <h1 className="text-3xl font-bold">CPU Usage Dashboard</h1>
        </header>

        <div className="space-y-3">
          <h1 className="text-xl font-bold">My Snapshot</h1>
          <p className="text-sm italic text-gray-400">
            These are your personal CPU usage statistics
          </p>
        </div>
        <div className="stats shadow mt-5">
          <div className="stat">
            <div className="stat-figure text-amber-500">
              <FontAwesomeIcon icon={faSignal} size="2xl" />
            </div>
            <div className="stat-title">Latest</div>
            <div>
              {/* <span className="loading loading-spinner loading-md"></span> */}
            </div>

            <div className="stat-value">
              {latestUserCpuUsage?.usage.toFixed(2)}%
            </div>

            <div className="stat-desc">
              As of {moment(latestUserCpuUsage?.timestamp).format('h:mma')}
            </div>
          </div>

          <div className="stat">
            <div className="stat-figure text-amber-500">
              <FontAwesomeIcon icon={faPercent} size="2xl" />
            </div>
            <div className="stat-title">Percentile</div>
            <div>
              {/* <span className="loading loading-spinner loading-md"></span> */}
            </div>

            <div className="stat-value">{userPercentile}</div>
            <div className="stat-desc">Across all users</div>
          </div>

          <div className="stat">
            <div className="stat-figure text-amber-500">
              <FontAwesomeIcon icon={faClock} size="2xl" />
            </div>
            <div className="stat-title">Hourly Average</div>
            <div>
              {/* <span className="loading loading-spinner loading-md"></span> */}
            </div>

            <div className="stat-value">
              {userLastHourAvgUsage?.toFixed(2)}%
            </div>
          </div>
        </div>
        <h1 className="text-xl font-bold my-5">
          High CPU Usage{' '}
          <div
            className="tooltip"
            data-tip="Users with a higher than average hourly CPU usage"
          >
            <i className="fa fa-info-circle fa-xs" aria-hidden="true"></i>
          </div>
        </h1>
        <div className="overflow-x-auto">
          <table className="table">
            <thead>
              <tr>
                <th></th>
                <th>User ID</th>
                <th>CPU Usage (%)</th>
                <th>Severity Level</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                {usersWithAboveAvgUsage?.map((row, i) => (
                  <>
                    <td>{i + 1}</td>
                    <td>{row.user.userUUID}</td>
                    <td>{row.userAvg.toFixed(2)}</td>
                    <td
                      className={
                        row.userAvg > 50
                          ? 'text-red-500'
                          : row.userAvg > 30
                            ? 'text-yellow-500'
                            : 'text-green-500'
                      }
                    >
                      {row.userAvg > 50
                        ? 'High'
                        : row.userAvg > 30
                          ? 'Medium'
                          : 'Low'}
                    </td>
                  </>
                ))}
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}

// angularFrontend/src/app/dashboard/dashboard.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import {
  Observable,
  Subscription,
  catchError,
  switchMap,
  timer,
  EMPTY,
  tap,
} from 'rxjs';
import { CpuUsage, User } from 'models';
import moment from 'moment';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css'],
})
export class DashboardComponent {
  latestUserCpuUsage: string = '';
  latestUserTimestamp: string = '';
  userLastHourAvgUsage: string = '';
  usersWithAboveAvgUsage: Array<{ user: User; userAvg: number }> | null = null;
  userPercentile: string = '';
  private subscription: Subscription = new Subscription();

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.subscription = timer(0, 5000)
      .pipe(
        switchMap(() => {
          return this.fetchData();
        })
      )
      .subscribe();
    this.subscription = timer(0, 5000)
      .pipe(
        switchMap(() => {
          return this.fetchLastHourAvg();
        })
      )
      .subscribe();
    this.subscription = timer(0, 5000)
      .pipe(
        switchMap(() => {
          return this.fetchUsersWithAboveAvgUsage();
        })
      )
      .subscribe();
    this.subscription = timer(0, 5000)
      .pipe(
        switchMap(() => {
          return this.fetchUserPercentile();
        })
      )
      .subscribe();
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  private fetchData(): Observable<CpuUsage> {
    return this.http.get<CpuUsage>('http://localhost:8080/cpu-usage').pipe(
      catchError((error: any) => {
        console.error('Error fetching CPU usage data:', error);
        return EMPTY;
      }),
      switchMap((data: CpuUsage) => {
        this.latestUserCpuUsage = data.usage.toFixed(2);
        this.latestUserTimestamp = this.getFormattedTime(data.timestamp);
        return EMPTY;
      })
    );
  }

  private fetchLastHourAvg(): Observable<number> {
    return this.http.get<number>('http://localhost:8080/last-hour-avg').pipe(
      catchError((error: any) => {
        console.error('Error fetching last hour average:', error);
        return EMPTY;
      }),
      switchMap((avg: number) => {
        this.userLastHourAvgUsage = avg.toFixed(2);
        return EMPTY;
      })
    );
  }

  private fetchUsersWithAboveAvgUsage(): Observable<Array<{
    user: User;
    userAvg: number;
  }> | null> {
    return this.http
      .get<Array<{ user: User; userAvg: number }> | null>(
        'http://localhost:8080/above-avg-usage-users'
      )
      .pipe(
        catchError((error: any) => {
          console.error(
            'Error fetching users with above average usage:',
            error
          );
          return EMPTY;
        }),
        tap((data: Array<{ user: User; userAvg: number }> | null | null) => {
          if (data) {
            this.usersWithAboveAvgUsage = data;
          }
        })
      );
  }

  private fetchUserPercentile(): Observable<number> {
    return this.http.get<number>('http://localhost:8080/user-percentile').pipe(
      catchError((error: any) => {
        console.error('Error fetching last hour average:', error);
        return EMPTY;
      }),
      switchMap((avg: number) => {
        this.userPercentile = avg.toFixed(2);
        return EMPTY;
      })
    );
  }

  private getFormattedTime(timestamp: number): string {
    return moment(timestamp).format('HH:mm:ss');
  }
}

<div class="ml-10 p-5">

  <header class="pb-5">
    <h1 class="text-3xl font-bold">CPU Usage Dashboard</h1>
  </header>


  <div class="space-y-3">
    <h1 class="text-xl font-bold">My Snapshot</h1>
    <p class="text-sm italic text-gray-400">These are your personal CPU usage statistics</p>
  </div>
  <div class="stats shadow mt-5">

    <div class="stat">
      <div class="stat-figure text-amber-500">
        <i class="fa fa-signal fa-2xl" aria-hidden="true"></i>
      </div>
      <div class="stat-title">Latest</div>
      <div *ngIf="latestUserCpuUsage === '' else latestUserCpuUsageDiv">
        <span class="loading loading-spinner loading-md"></span>
      </div>
      
      <ng-template #latestUserCpuUsageDiv>
        <div class="stat-value">{{ latestUserCpuUsage }}%</div>
      </ng-template>
      
      <div class="stat-desc">As of {{ latestUserTimestamp }}</div>
    </div>
    
    <div class="stat">
      <div class="stat-figure text-amber-500">
        <i class="fa fa-percent fa-2xl" aria-hidden="true"></i>
      </div>
      <div class="stat-title">Percentile</div>
      <div *ngIf="userPercentile === '' else userPercentileDiv">
        <span class="loading loading-spinner loading-md"></span>
      </div>
      
      <ng-template #userPercentileDiv>
        <div class="stat-value">{{ userPercentile }}</div>
      </ng-template>
      <div class="stat-desc">Across all users</div>
    </div>
    
    <div class="stat">
      <div class="stat-figure text-amber-500">
        <i class="fa fa-clock fa-2xl" aria-hidden="true"></i>
      </div>
      <div class="stat-title">Hourly Average</div>
      <div *ngIf="userLastHourAvgUsage === '' else userLastHourAvgUsageDiv">
        <span class="loading loading-spinner loading-md"></span>
      </div>
      
      <ng-template #userLastHourAvgUsageDiv>
        <div class="stat-value">{{ userLastHourAvgUsage }}%</div>
      </ng-template>
    </div>
    
  </div>
  <h1 class="text-xl font-bold my-5">High CPU Usage <div class="tooltip" data-tip="Users with a higher than average hourly CPU usage">
    <i class="fa fa-info-circle fa-xs" aria-hidden="true"></i>
  </div></h1>
  <div class="overflow-x-auto">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>User ID</th>
          <th>CPU Usage (%)</th>
          <th>Severity Level</th>
        </tr>
      </thead>
      <tbody>
          <tr *ngFor="let row of usersWithAboveAvgUsage; let i = index">
            <td>{{ i + 1 }}</td>
            <td>{{ row.user.userUUID }}</td>
            <td>{{ row.userAvg }}</td>
            <td [ngClass]="{
              'text-red-500': row.userAvg > 50,
              'text-amber-500': row.userAvg <= 50 && row.userAvg > 30,
              'text-green-500': row.userAvg <= 30
            }">
              {{ row.userAvg > 50 ? 'High' : row.userAvg > 30 ? 'Medium' : 'Low' }}
            </td>    
          </tr>
      </tbody>
    </table>
  </div>
</div>
